### PR TITLE
Manage opening of WARC 1.1 and update identification of WARC 1.0

### PR DESCRIPTION
**Pull request by sparkhi**
Updates to support Warc 1.1, In addition to that, there are changes to 
1) Support newly created signature for WARC1.1 (fmt/1355) which is separate from generic WARC 
2) Fixed an NPE in CLI which happened when the date string in WARC included fractions of second
3) Added a couple of developers names in parent POM

[UPDATE Jeremie] Fix https://github.com/digital-preservation/droid/issues/365

### CODE REVIEW

**Comment by jcharlet** [comment]
@sparkhi can you please provide test files on the repo and link to them here? 
Should we add a test case for each test file?

**Comment by sparkhi** [comment]
The CI failure on Travis has a miniscule chance of happening when the timestamp for the file has milliseconds part as zero. I'll fix that as well.

**Comment by sparkhi** [comment]
[testing-365.zip](https://github.com/digital-preservation/droid/files/4134443/testing-365.zip)
The zip contains test data. There is at least one file each which will identify against each of the 3 puids for warc. There are a couple other files as well. One error file to make sure there is no bad effect when a file is not identified

**Comment by sparkhi** [comment]
[devtest-467.zip](https://github.com/digital-preservation/droid/files/4134587/devtest-467.zip)
The signature file includes new signature for 1.0 - fmt/1355

**Pull request merged**
