### PR TITLE
Java 8 and Java 9 updates for droid

### PR DESCRIPTION
**Pull request by rhubner**
Fixed pull request from @adamretter 

- Drop Java 7 support, Java8 is minimum
- Add Java 9 support.

### CODE REVIEW

**Comment by rhubner** [comment]
[Java 9 work](https://trello.com/c/pbVqzaHE/108-java-9-work)

**Comment by jcharlet** [comment]
hi @adamretter, @rhubner 
while testing the 6.5 snapshot for release, I found out we have those warning logs being repeated about hikari. 
Any idea what it is about, is it critical, worth fixing? 

```
2020-01-09 07:52:52,715  INFO Starting DROID.
2020-01-09 07:52:55,819  INFO Creating profile: 1578549175819
2020-01-09 07:52:55,862  INFO Opening profile: 1578549175819
2020-01-09 07:52:58,102  INFO HikariPool-1 - Starting...
2020-01-09 07:52:58,107  WARN Registered driver with driverClassName=org.apache.derby.jdbc.EmbeddedDriver was not found, trying direct instantiation.
2020-01-09 07:52:58,117  INFO HikariPool-1 - Driver does not support get/set network timeout for connections. (Feature not implemented: No details.)
2020-01-09 07:52:58,121  INFO HikariPool-1 - Start completed.
2020-01-09 07:53:01,630  INFO HikariPool-1 - Starting...
2020-01-09 07:53:01,630  WARN Registered driver with driverClassName=org.apache.derby.jdbc.EmbeddedDriver was not found, trying direct instantiation.
2020-01-09 07:53:01,632  INFO HikariPool-1 - Driver does not support get/set network timeout for connections. (Feature not implemented: No details.)
2020-01-09 07:53:01,632  INFO HikariPool-1 - Start completed.
2020-01-09 07:53:01,646  INFO HikariPool-1 - Starting...
2020-01-09 07:53:01,646  WARN Registered driver with driverClassName=org.apache.derby.jdbc.EmbeddedDriver was not found, trying direct instantiation.
2020-01-09 07:53:01,647  INFO HikariPool-1 - Driver does not support get/set network timeout for connections. (Feature not implemented: No details.)
2020-01-09 07:53:01,647  INFO HikariPool-1 - Start completed.
2020-01-09 07:53:01,655  INFO HikariPool-1 - Starting...
2020-01-09 07:53:01,655  WARN Registered driver with driverClassName=org.apache.derby.jdbc.EmbeddedDriver was not found, trying direct instantiation.
2020-01-09 07:53:01,657  INFO HikariPool-1 - Driver does not support get/set network timeout for connections. (Feature not implemented: No details.)
2020-01-09 07:53:01,657  INFO HikariPool-1 - Start completed.
2020-01-09 07:53:01,666  INFO HikariPool-1 - Starting...
2020-01-09 07:53:01,666  WARN Registered driver with driverClassName=org.apache.derby.jdbc.EmbeddedDriver was not found, trying direct instantiation.
2020-01-09 07:53:01,668  INFO HikariPool-1 - Driver does not support get/set network timeout for connections. (Feature not implemented: No details.)
2020-01-09 07:53:01,668  INFO HikariPool-1 - Start completed.
2020-01-09 07:53:01,851  INFO HikariPool-1 - Starting...
2020-01-09 07:53:01,851  WARN Registered driver with driverClassName=org.apache.derby.jdbc.EmbeddedDriver was not found, trying direct instantiation.
2020-01-09 07:53:01,856  INFO HikariPool-1 - Driver does not support get/set network timeout for connections. (Feature not implemented: No details.)
2020-01-09 07:53:01,859  INFO HikariPool-1 - Start completed.
2020-01-09 07:53:02,030  INFO Saving profile [/home/jeremie/.droid6/profiles/1578549175819/db] to [/home/jeremie/.droid6/profile_templates/schema 6.04/profile.template]
2020-01-09 07:53:02,159  INFO HikariPool-1 - Starting...
2020-01-09 07:53:02,160  WARN Registered driver with driverClassName=org.apache.derby.jdbc.EmbeddedDriver was not found, trying direct instantiation.
2020-01-09 07:53:02,169  INFO HikariPool-1 - Driver does not support get/set network timeout for connections. (Feature not implemented: No details.)
2020-01-09 07:53:02,175  INFO HikariPool-1 - Start completed.
2020-01-09 07:53:04,837  INFO HikariPool-1 - Starting...
2020-01-09 07:53:04,837  WARN Registered driver with driverClassName=org.apache.derby.jdbc.EmbeddedDriver was not found, trying direct instantiation.
2020-01-09 07:53:04,838  INFO HikariPool-1 - Driver does not support get/set network timeout for connections. (Feature not implemented: No details.)
2020-01-09 07:53:04,839  INFO HikariPool-1 - Start completed.
2020-01-09 07:53:04,868  INFO Saving profile [/home/jeremie/.droid6/profiles/1578549175819/db] to [/home/jeremie/.droid6/profile_templates/schema 6.04/profile.91.template]
2020-01-09 07:53:04,953  INFO HikariPool-1 - Starting...
2020-01-09 07:53:04,953  WARN Registered driver with driverClassName=org.apache.derby.jdbc.EmbeddedDriver was not found, trying direct instantiation.
2020-01-09 07:53:04,959  INFO HikariPool-1 - Driver does not support get/set network timeout for connections. (Feature not implemented: No details.)
2020-01-09 07:53:04,959  INFO HikariPool-1 - Start completed.
2020-01-09 07:53:04,998  INFO Attempting state change [INITIALISING] to [VIRGIN]
```

Introduced between 6.4 release and this pull request. I suppose introduced when Adam you migrated to hikari on https://github.com/digital-preservation/droid/pull/167 , but I cannot test on the merge commit for that PR, I get an exception while starting the UI.

**Comment by adamretter** [comment]
@jcharlet I don't think those warnings are anything to worry about... if they were, then the database wouldn't work at all ;-)

**Comment by jcharlet** [comment]
ok will ignore then, thanks @adamretter

**Pull request merged**
