### PR TITLE
Dbconnections

### PR DESCRIPTION
**Pull request by nishihatapalmer**
Removes the factory which created a new connection pool for everything that just wanted a connection pool.

See issue https://github.com/digital-preservation/droid/issues/362

Now we just use the connection pool to give classes connections, rather than creating a new pool for each class.

Needs some testing, as the reason for using the factory in the first place is not defined.  There were some comments about fixing some spring initialization error, but there are no recorded issues in GitHub about this.

Regardless, using a factory to create a new connection pool is not the solution to initialization issues in the connection pool, as we don't want separate connection pools for each class.

### CODE REVIEW

**Comment by nishihatapalmer** [comment]
So, merging latest master to resolve the conflicts was pretty easy, but now I get weird spring initialization problems.  

The data source is now being initialized with a null HikariConfig object, even though nothing in the spring-jpa has changed.  I guess this was why the factory was erroneously introduced - to try to force spring to initialize objects in the right order.

Something is clearly weird here.  No change to spring configuration but changes to the order of initialization.

**Comment by nishihatapalmer** [comment]
OK - @rhubner has provided a better solution - to set the DerbyPooledDataSourceFactory isSingleton() method to true.  Which apparently ensures the factory only creates a single object (I thought it meant only one factory was produced...)

**Comment by jcharlet** [comment]
thanks Matt for looking into this, too bad Radek provided a solution already, hope you didn't waste too much time!

**Comment by jcharlet** [comment]
sorry too quick to press buttons, I suppose you might want to keep your work aside

**Pull request closed without merging**
