### PR TITLE
Manage special folders (forbidden, shortcuts)

### PR DESCRIPTION
**Pull request by sparkhi**
[Update Jeremie]

# Issues
https://github.com/digital-preservation/droid/issues/395
https://github.com/digital-preservation/droid/issues/406

# Solution
- Added a validation to make sure non - fs folders like 'Libraries' onwindows cannot be added
- manage forbidden files and folders: prevent breaking + show as forbidden in GUI

# Acceptance Test
NOTE: The testing can only be done on Windows OS for this fix, other OSs should not see any change.

1. Open Droid GUI
2. Create a new profile
3. Click on the 'add' button to bring up file chooser dialog
4. Pick one of the Windows 'virtual collection' folder (e.g. Libraries, Documents) which does not map directly to file system
5. You should see an error message informing you that the folder is not allowed.
6. If there is more than one non-file-system folder picked in step #4 above, all such folder names should appear in the error
7. If there is a combination of non-file-system folder and a file-system-folder, the error message should inform only about the non file-system folder
8. If all folders picked in step #4 are valid file-system folders, they should all be added to the profiling dialog.

### CODE REVIEW

**Comment by sparkhi** [comment]
### Acceptance Test

NOTE: The testing can only be done on Windows OS for this fix, other OSs should not see any change.

1. - Open Droid GUI
2. - Create a new profile
3. - Click on the 'add' button to bring up file chooser dialog
4. - Pick one of the Windows 'virtual collection' folder (e.g. Libraries, Documents) which does not map directly to file system
5. - You should see an error message informing you that the folder is not allowed. 
6. - If there is more than one non-file-system folder picked in step #4 above, all such folder names should appear in the error 
7 - If there is a combination of non-file-system folder and a file-system-folder, the error message should inform only about the non file-system folder 
8 - If all folders picked in step #4 are valid file-system folders, they should all be added to the profiling dialog.

**Comment by jcharlet** [comment]
fix https://github.com/digital-preservation/droid/issues/395

**Comment by jcharlet** [comment]
works on libraries and similar folders, but crashes on forbidden folders

**Comment by jcharlet** [comment]
as discussed with Saurab, this PR will fix as well https://github.com/digital-preservation/droid/issues/406

**Pull request merged**
